### PR TITLE
Fix OTP get/list for row 1

### LINKED ISSUE #296: picotool otp get and otp list do not display OTP row 1
```bash
$./picotool otp list 1
DEBUG filter_otp: selector '1' resolved to row 1
    (row has no sub-fields)

$./picotool otp get 1
<displays no output>
```

Contrast with any other row, let's say 3:

```bash
$./picotool otp list 3
ROW 0x0003: OTP_DATA_CHIPID3 (Part 4/4)
        "Bits 63:48 of public device ID (ECC)"
    (row has no sub-fields)

$./picotool otp get 3
ROW 0x0003: OTP_DATA_CHIPID3 (Part 4/4)
        "Bits 63:48 of public device ID (ECC)"

    VALUE 0x3358ad
```

The bug is as a result of this line:

```c
uint32_t last_reg_row = 1; // invalid
```

in both:

```c
otp_get_command::execute();
otp_list_command::execute();
```

I suggest initialising last_reg_row to 0xffffffff (or any other invalid row number) instead.

With last_reg_row initialised to 0xffffffff:

```bash
$ ./picotool otp list 1
ROW 0x0001: OTP_DATA_CHIPID1 (Part 2/4)
        "Bits 31:16 of public device ID (ECC)"
    (row has no sub-fields)
$ ./picotool otp get 1
ROW 0x0001: OTP_DATA_CHIPID1 (Part 2/4)
        "Bits 31:16 of public device ID (ECC)"

    VALUE 0x09673b
```

### PR DESCRIPTION
**Pull request by will-v-pi**
The last_reg_row variable was not being initialised to an invalid value

Fixes #296

### CODE REVIEW

File: main.cpp [hunk 1]
```diff
@@ -7669,7 +7669,7 @@ bool otp_get_command::execute(device_map &devices) {
     picoboot_memory_access raw_access(con);
     auto model = raw_access.get_model();
     auto matches = filter_otp(settings.otp.selectors, otp_cmd_max_bits(), settings.otp.fuzzy);
-    uint32_t last_reg_row = 1; // invalid
+    uint32_t last_reg_row = 0xffffffff; // invalid
```
Comment (lurch) [inline main.cpp]: Would it be worth creating a `#define` for this "invalid value" in one of the header files?

**Review by kilograham — APPROVED** [review]
