### PR TITLE
Fix fread unused_result warning

### LINKED ISSUE #91: Minor compiler warning on build, fread return value unused
Compiling picotool under Ubuntu 20.04 and GCC 9.4 results in the following warning about not checking the the source file read completed properly:

````
Scanning dependencies of target picotool
[ 25%] Building CXX object CMakeFiles/picotool.dir/main.cpp.o
/home/earle/src/picotool/main.cpp: In member function ‘virtual void file_memory_access::read(uint32_t, uint8_t*, uint32_t, bool)’:
/home/earle/src/picotool/main.cpp:869:22: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
  869 |                 fread(buffer, this_size, 1, file);
      |                 ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 50%] Building CXX object CMakeFiles/picotool.dir/picoboot_connection/picoboot_connection_cxx.cpp.o
[ 75%] Building C object CMakeFiles/picotool.dir/picoboot_connection/picoboot_connection.c.o
[100%] Linking CXX executable picotool
[100%] Built target picotool
````

### PR DESCRIPTION
**Pull request by earlephilhower**
Check the read of the source binary succeeded, and if not generate an exception and let the user know.

Fixes #91

### CODE REVIEW

File: main.cpp [hunk 1]
```diff
@@ -866,7 +866,12 @@ struct file_memory_access : public memory_access {
                 this_size = std::min(size, result.first.max_offset - result.first.offset);
                 assert(this_size);
                 fseek(file, result.second + result.first.offset, SEEK_SET);
-                fread(buffer, this_size, 1, file);
+                auto read_bytes = fread(buffer, 1, this_size, file);
+                if (this_size != read_bytes) {
+                    std::stringstream err;
```
Comment (kilograham) [inline main.cpp:871]: Thanks, but preferable to use the `fail` function

**Review by kilograham — CHANGES_REQUESTED** [review]

**Review by kilograham — APPROVED** [review]
